add_newline = false
command_timeout = 50

format = """
$directory$git_branch$git_commit$git_status$status $nodejs$python$rust$golang$docker_context$cmd_duration
$username"""

[username]
format = "[<](bold white)[$user](bold #8f86e8)[>](bold white) "
disabled = false
show_always = true

[status]
format = "[✗ $status]($style) "
style = "bold #eb6f92"
disabled = false

[cmd_duration]
min_time = 2000
format = "[󰅐 $duration]($style) "
style = "bold #94a3b8"

[directory]
truncation_length = 0
truncation_symbol = ""
home_symbol = "󰋜 "
style = "bold #8f86e8"
format = "[󰉖]($style)[ $path ](bold #8f86e8)"

[git_branch]
format = "[ $branch]($style) "
style = "bold #86efac"

[git_commit]
commit_hash_length = 7
format = "[ $hash]($style) "
style = "bold #e8a0bf"

[git_status]
style = "bold #86efac"
format = '[$all_status$ahead_behind]($style) '
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = ""
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[nodejs]
format = "[ $version]($style) "
style = "bold #94a3b8"
disabled = false

[python]
format = "[ $version]($style) "
style = "bold #94a3b8"
disabled = false

[rust]
format = "[ $version]($style) "
style = "bold #94a3b8"
disabled = false

[golang]
format = "[ $version]($style) "
style = "bold #94a3b8"
disabled = false

[docker_context]
format = "[ $context]($style) "
style = "bold #94a3b8"
disabled = false

[package]
disabled = true
[hostname]
disabled = true
[shell]
disabled = true
[battery]
disabled = true
[time]
disabled = true
